name: RedstonePvp
version: '${project.version}'
main: me.zxoir.redstonepvp.RedstonePvp
description: "RedstonePvp plugin"
commands:
  itemframeclicker:
    description: ItemFrameClicker command
    aliases: [ifc, ic]
    permission: redstonepvp.itemframeclicker.command
  trash:
    description: Trash Command
  transfer:
    description: Transfer points command
  points:
    description: Points Command
  friend:
    description: Friend command
    aliases: [friends, f]
  duel:
    description: Duel command
    aliases: [d, duels]
permissions:
  "redstonepvp.itemframeclicker.command":
    description: Permission to use the itemframe clicker command
    default: op
  "redstonepvp.points.command":
    description: Permission to use the points command
    default: op
  "redstonepvp.duel.admin":
    description: Permission to manage duels
    default: op